### ISSUE TITLE
demo.py not working 

### ISSUE THREAD

**Issue by dmardanbeigi** [Gy920/segment-anything-2-real-time#19]
I get this error
`TypeError: SAM2Base.__init__() got an unexpected keyword argument 'no_obj_embed_spatial'`
when I call the `build_sam2_camera_predictor` in the demo file

**Comment by Gy920** [comment]
It works fine on my end, maybe you need to uninstall SAM-2 using `pip uninstall SAM-2` and then reinstall it using ` pip install -e .`"

**Comment by dmardanbeigi** [comment]
I reinstalled the SAM-2 using `pip install ultralytics`
I cannot use `pip install -e .` because it throws me nonsense undefined CUDA_HOME error even though the CUDA_HOME is defined 
```shell
PS C:\Users\[user]\Code\investigation\[project_directory]>pip install -e .
Obtaining file:///C:/Users/[user]/Code/investigation/[project_directory]
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Using existing CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6
      Current CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6
      Traceback (most recent call last):
        File "C:\Users\[user]\Code\investigation\[project_directory]\sam2-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\[user]\Code\investigation\[project_directory]\sam2-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\[user]\Code\investigation\[project_directory]\sam2-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\setuptools\build_meta.py", line 483, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
        File "<string>", line 57, in get_extensions
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1078, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1216, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-[hash]\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. Please set it to your CUDA install root.')
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

```

**Comment by Gy920** [comment]
If you use `pip install ultralytics` to instasll SAM2, you'll actually be using the SAM2 code integrated into ultralytics, not the code from this repository. They may not be compatible. 

Unfortunately, I don't have any experience using CUDA on Windows, so I can't help with the CUDA_HOME issue.
